### ISSUE TITLE
Hello,please help me unpack and Repack .pna

### ISSUE THREAD

**Issue by ghost** [Inori/FuckGalEngine#56]
i'm really new and never used .cpp and stuffs before,what i know is i have to use comand prompt right...?
I want to use ahdprc to  unpack my .pna files and repack it back,but i dont know how to use the .cpp and stuffs.

Could anyone kindheartly teach me the ways how to use it.Thank you !

**Comment by Inori** [comment]
@sgqy

**Comment by ghost** [comment]
Pls help...

**Comment by sgqy** [comment]
Hello.
You should run in `cmd.exe`.
Press `Win + R`, input `cmd.exe` and press `Enter`.

If your `staff.pna` is stored in `F:\mydocs`, copy the `ahdprc.exe` into that folder.
In command prompt, input `cd /d F:\mydocs`.
Then, `ahdprc.exe pna -u staff.pna`.
Expected behavior is that the `staff` folder is created.
Do not modify the file `staff\_cht.bin`.
After your edition, run `ahdprc.exe pna -r staff`.
Expected behavior is that there will be a new file called `staff.pna` (or rewritten).

Note that the tool is so old, may cannot satisfy what you need.
Best wishes.

**Comment by ghost** [comment]
Hello.I'm sorry but,i don't know where the ahdprc.exe is,when i tried to compile the cpp there's a fatal error on #include <princess.h> no such file or directory.But i've already put the princess.h in the same directory.I don't know what to do with that.

I use g++ compiler.Thank you.

**Comment by ghost** [comment]
Help me pls...

**Comment by sgqy** [comment]
Oh... the library is a private library, which is made by `CodeBlocks` with `GCC(MinGW) 4.7.1` in Windows OS.
It was a library made for basic I/O operations, but with too old years, I missed it, unfortunately.
Try these commands to build. (for example)
```
g++ -c -o main.o main.cpp
g++ -c -o package.o package.cpp
# other source files ...
g++ -o main.exe main.o package.o $other_obj_files libprincess.a
```

**Comment by ghost** [comment]
![IMG20220413225001](https://user-images.githubusercontent.com/81911243/163220261-ecf912df-c2c5-4fc2-b5fd-4875ee8743ff.jpg)

Still can't,uh,if you don't mind could you just give me a link to download the ahdprc.exe because i've wasted many time for this one actually :) Thank you !

**Comment by Inori** [comment]
> Still can't,uh,if you don't mind could you just give me a link to download the ahdprc.exe because i've wasted many time for this one actually :) Thank you !

Don't you think you are wasting the time of the developer?

**Comment by sgqy** [comment]
If you want to `#include` something. The command should be like this.
`g++ -c -o main.o main.cpp -Ilib`

**Comment by ghost** [comment]
Ah...yeah,sorry if that wasting your time,but i'll keep trying,thanks for your time man,i got new experience from that,i'll try that command.Thanks again.
