### ISSUE TITLE
PackNameTxt

### ISSUE THREAD

**Issue by imKota** [Inori/FuckGalEngine#58]
Hello,  @Inori!

**Comment by Inori** [comment]
The script is used to generate a hash table of strings, the hash value is calculated using the original Jananese text.
The script stores [hash_key, translated_string] pairs in the output binary file.

Then during game runtime, the code in [MinoriPatch.cpp](https://github.com/Inori/FuckGalEngine/blob/master/Minori/Minori/MinoriPatch/MinoriPatch.cpp#L297) will calculate the hash of the game's text using the same algorithm as the script does.
This way, we can index the translated strings using hash value, and replace the original Japanese text with the found one.

So if the name is not displayed correctly, there must be hash match errors, possibly you are using wrong translated
name pairs or wrong encodings.
I can't tell you the details because I really don't remember such details after so many years...
You can attach the debugger to see what's going wrong.

**Comment by imKota** [comment]
@Inori I know how it works. 
The problem is that PackAsyncScript.py does not generate the file correctly.

For example, the original file from "罪之光Rendezvous"
[cnname.acr.zip](https://github.com/Inori/FuckGalEngine/files/8672265/cnname.acr.zip)
And pairs of Japanese-Chinese names (working file)
[cnname.txt](https://github.com/Inori/FuckGalEngine/files/8672296/cnname.txt)
New generated file (Japanese-Chinese names)
[cnname_new.zip](https://github.com/Inori/FuckGalEngine/files/8672314/cnname_new.zip)

**Comment by imKota** [comment]
Thank you, for the answer.
I ended up writing myself :)
